### Matriz varianza y covariante

In [19]:
import numpy as np

In [32]:
#Arreglo
datos = np.array(np.random.random((4, 3)))

print(datos)
type(datos)

[[0.54694056 0.22437047 0.47767357]
 [0.82926391 0.42874156 0.58156064]
 [0.99544406 0.5803357  0.19692609]
 [0.66416719 0.98330059 0.20652921]]


numpy.ndarray

In [40]:
datos.shape
covarianza = np.cov(datos)
varianza = np.var(datos)

print('Varianza es ' + str(varianza))

print('covarianza es ' + str(covarianza))



Varianza es 0.07055114207403375
covarianza es [[ 0.02883531  0.03084396  0.01534894 -0.04466705]
 [ 0.03084396  0.04085479  0.05091056 -0.02219452]
 [ 0.01534894  0.05091056  0.15949147  0.08846314]
 [-0.04466705 -0.02219452  0.08846314  0.15244207]]
